/**
 * Türkiye İl ve İlçe Listesi
 * Büyük şehirlerin ilçeleri ve diğer illerin merkez ilçeleri
 */

export const TURKEY_LOCATIONS: Record<string, string[]> = {
  'Adana': ['Seyhan', 'Yüreğir', 'Çukurova', 'Sarıçam', 'Ceyhan', 'Karataş', 'Kozan', 'Pozantı', 'İmamoğlu', 'Karaisalı', 'Aladağ', 'Feke', 'Saimbeyli', 'Tufanbeyli', 'Yumurtalık'],
  'Adıyaman': ['Merkez', 'Besni', 'Çelikhan', 'Gerger', 'Gölbaşı', 'Kahta', 'Samsat', 'Sincik', 'Tut'],
  'Afyonkarahisar': ['Merkez', 'Bolvadin', 'Çay', 'Dazkırı', 'Dinar', 'Emirdağ', 'Hocalar', 'İhsaniye', 'İscehisar', 'Kızılören', 'Sandıklı', 'Sinanpaşa', 'Sultandağı', 'Şuhut'],
  'Ağrı': ['Merkez', 'Diyadin', 'Doğubayazıt', 'Eleşkirt', 'Hamur', 'Patnos', 'Taşlıçay', 'Tutak'],
  'Amasya': ['Merkez', 'Göynücek', 'Gümüşhacıköy', 'Hamamözü', 'Merzifon', 'Suluova', 'Taşova'],
  'Ankara': ['Çankaya', 'Keçiören', 'Yenimahalle', 'Mamak', 'Etimesgut', 'Sincan', 'Altındağ', 'Pursaklar', 'Gölbaşı', 'Polatlı', 'Beypazarı', 'Elmadağ', 'Kahramankazan', 'Akyurt', 'Çubuk', 'Ayaş', 'Bala', 'Çamlıdere', 'Evren', 'Güdül', 'Haymana', 'Kızılcahamam', 'Nallıhan', 'Şereflikoçhisar'],
  'Antalya': ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Aksu', 'Döşemealtı', 'Alanya', 'Manavgat', 'Kemer', 'Kaş', 'Kumluca', 'Serik', 'Korkuteli', 'Gazipaşa', 'Finike', 'Elmalı', 'İbradı', 'Akseki', 'Demre', 'Gündoğmuş'],
  'Artvin': ['Merkez', 'Ardanuç', 'Arhavi', 'Borçka', 'Hopa', 'Kemalpaşa', 'Murgul', 'Şavşat', 'Yusufeli'],
  'Aydın': ['Efeler', 'Kuşadası', 'Didim', 'Nazilli', 'Söke', 'Germencik', 'İncirliova', 'Koçarlı', 'Köşk', 'Bozdoğan', 'Buharkent', 'Çine', 'Karacasu', 'Karpuzlu', 'Kuyucak', 'Sultanhisar', 'Yenipazar'],
  'Balıkesir': ['Altıeylül', 'Karesi', 'Bandırma', 'Edremit', 'Gönen', 'Ayvalık', 'Burhaniye', 'Bigadiç', 'Havran', 'Sındırgı', 'Susurluk', 'Dursunbey', 'İvrindi', 'Kepsut', 'Manyas', 'Savaştepe', 'Erdek', 'Balya', 'Gömeç', 'Marmara'],
  'Bilecik': ['Merkez', 'Bozüyük', 'Gölpazarı', 'İnhisar', 'Osmaneli', 'Pazaryeri', 'Söğüt', 'Yenipazar'],
  'Bingöl': ['Merkez', 'Genç', 'Karlıova', 'Kiğı', 'Solhan', 'Adaklı', 'Yayladere', 'Yedisu'],
  'Bitlis': ['Merkez', 'Adilcevaz', 'Ahlat', 'Güroymak', 'Hizan', 'Mutki', 'Tatvan'],
  'Bolu': ['Merkez', 'Gerede', 'Göynük', 'Kıbrıscık', 'Mengen', 'Mudurnu', 'Seben', 'Dörtdivan', 'Yeniçağa'],
  'Burdur': ['Merkez', 'Ağlasun', 'Altınyayla', 'Bucak', 'Çavdır', 'Çeltikçi', 'Gölhisar', 'Karamanlı', 'Kemer', 'Tefenni', 'Yeşilova'],
  'Bursa': ['Osmangazi', 'Nilüfer', 'Yıldırım', 'Gemlik', 'Mudanya', 'İnegöl', 'Gürsu', 'Kestel', 'Mustafakemalpaşa', 'Orhangazi', 'Karacabey', 'İznik', 'Yenişehir', 'Harmancık', 'Büyükorhan', 'Keles', 'Orhaneli'],
  'Çanakkale': ['Merkez', 'Ayvacık', 'Bayramiç', 'Biga', 'Bozcaada', 'Çan', 'Eceabat', 'Ezine', 'Gelibolu', 'Gökçeada', 'Lapseki', 'Yenice'],
  'Çankırı': ['Merkez', 'Atkaracalar', 'Bayramören', 'Çerkeş', 'Eldivan', 'Ilgaz', 'Kızılırmak', 'Korgun', 'Kurşunlu', 'Orta', 'Şabanözü', 'Yapraklı'],
  'Çorum': ['Merkez', 'Alaca', 'Bayat', 'Boğazkale', 'Dodurga', 'İskilip', 'Kargı', 'Laçin', 'Mecitözü', 'Oğuzlar', 'Ortaköy', 'Osmancık', 'Sungurlu', 'Uğurludağ'],
  'Denizli': ['Pamukkale', 'Merkezefendi', 'Acıpayam', 'Buldan', 'Çal', 'Çameli', 'Çardak', 'Çivril', 'Güney', 'Honaz', 'Kale', 'Sarayköy', 'Tavas', 'Babadağ', 'Bekilli', 'Baklan', 'Bozkurt', 'Beyağaç', 'Serinhisar'],
  'Diyarbakır': ['Bağlar', 'Kayapınar', 'Sur', 'Yenişehir', 'Bismil', 'Çermik', 'Çınar', 'Çüngüş', 'Dicle', 'Eğil', 'Ergani', 'Hani', 'Hazro', 'Kocaköy', 'Kulp', 'Lice', 'Silvan'],
  'Edirne': ['Merkez', 'Enez', 'Havsa', 'İpsala', 'Keşan', 'Lalapaşa', 'Meriç', 'Süloğlu', 'Uzunköprü'],
  'Elazığ': ['Merkez', 'Ağın', 'Alacakaya', 'Arıcak', 'Baskil', 'Karakoçan', 'Keban', 'Kovancılar', 'Maden', 'Palu', 'Sivrice'],
  'Erzincan': ['Merkez', 'Çayırlı', 'İliç', 'Kemah', 'Kemaliye', 'Otlukbeli', 'Refahiye', 'Tercan', 'Üzümlü'],
  'Erzurum': ['Yakutiye', 'Palandöken', 'Aziziye', 'Aşkale', 'Çat', 'Hınıs', 'Horasan', 'İspir', 'Karaçoban', 'Karayazı', 'Köprüköy', 'Narman', 'Oltu', 'Olur', 'Pasinler', 'Pazaryolu', 'Şenkaya', 'Tekman', 'Tortum', 'Uzundere'],
  'Eskişehir': ['Odunpazarı', 'Tepebaşı', 'Alpu', 'Beylikova', 'Çifteler', 'Günyüzü', 'Han', 'İnönü', 'Mahmudiye', 'Mihalgazi', 'Mihalıççık', 'Sarıcakaya', 'Seyitgazi', 'Sivrihisar'],
  'Gaziantep': ['Şahinbey', 'Şehitkamil', 'Oğuzeli', 'Nizip', 'İslahiye', 'Nurdağı', 'Araban', 'Yavuzeli', 'Karkamış'],
  'Giresun': ['Merkez', 'Alucra', 'Bulancak', 'Çamoluk', 'Çanakçı', 'Dereli', 'Doğankent', 'Espiye', 'Eynesil', 'Görele', 'Güce', 'Keşap', 'Piraziz', 'Şebinkarahisar', 'Tirebolu', 'Yağlıdere'],
  'Gümüşhane': ['Merkez', 'Kelkit', 'Köse', 'Kürtün', 'Şiran', 'Torul'],
  'Hakkari': ['Merkez', 'Çukurca', 'Şemdinli', 'Yüksekova'],
  'Hatay': ['Antakya', 'İskenderun', 'Dörtyol', 'Reyhanlı', 'Samandağ', 'Defne', 'Arsuz', 'Kırıkhan', 'Payas', 'Erzin', 'Hassa', 'Yayladağı', 'Kumlu', 'Altınözü', 'Belen'],
  'Isparta': ['Merkez', 'Aksu', 'Atabey', 'Eğirdir', 'Gelendost', 'Gönen', 'Keçiborlu', 'Senirkent', 'Sütçüler', 'Şarkikaraağaç', 'Uluborlu', 'Yalvaç', 'Yenişarbademli'],
  'Mersin': ['Akdeniz', 'Mezitli', 'Toroslar', 'Yenişehir', 'Tarsus', 'Erdemli', 'Silifke', 'Anamur', 'Mut', 'Bozyazı', 'Aydıncık', 'Çamlıyayla', 'Gülnar'],
  'İstanbul': ['Kadıköy', 'Beşiktaş', 'Bakırköy', 'Sarıyer', 'Ataşehir', 'Üsküdar', 'Pendik', 'Beylikdüzü', 'Başakşehir', 'Maltepe', 'Kartal', 'Fatih', 'Beyoğlu', 'Şişli', 'Bahçelievler', 'Zeytinburnu', 'Esenler', 'Bağcılar', 'Güngören', 'Küçükçekmece', 'Avcılar', 'Esenyurt', 'Büyükçekmece', 'Silivri', 'Çatalca', 'Arnavutköy', 'Eyüpsultan', 'Gaziosmanpaşa', 'Sultangazi', 'Kağıthane', 'Beykoz', 'Ümraniye', 'Sancaktepe', 'Çekmeköy', 'Sultanbeyli', 'Tuzla', 'Şile', 'Adalar', 'Bayrampaşa'],
  'İzmir': ['Konak', 'Bornova', 'Karşıyaka', 'Bayraklı', 'Çiğli', 'Gaziemir', 'Buca', 'Karabağlar', 'Narlıdere', 'Balçova', 'Güzelbahçe', 'Urla', 'Çeşme', 'Foça', 'Menemen', 'Menderes', 'Torbalı', 'Tire', 'Ödemiş', 'Bergama', 'Kemalpaşa', 'Dikili', 'Aliağa', 'Seferihisar', 'Kınık', 'Kiraz', 'Bayındır', 'Beydağ', 'Selçuk', 'Karaburun'],
  'Kars': ['Merkez', 'Akyaka', 'Arpaçay', 'Digor', 'Kağızman', 'Sarıkamış', 'Selim', 'Susuz'],
  'Kastamonu': ['Merkez', 'Abana', 'Ağlı', 'Araç', 'Azdavay', 'Bozkurt', 'Cide', 'Çatalzeytin', 'Daday', 'Devrekani', 'Doğanyurt', 'Hanönü', 'İhsangazi', 'İnebolu', 'Küre', 'Pınarbaşı', 'Seydiler', 'Şenpazar', 'Taşköprü', 'Tosya'],
  'Kayseri': ['Melikgazi', 'Kocasinan', 'Talas', 'Hacılar', 'İncesu', 'Develi', 'Yahyalı', 'Pınarbaşı', 'Bünyan', 'Tomarza', 'Akkışla', 'Felahiye', 'Özvatan', 'Sarıoğlan', 'Sarız', 'Yeşilhisar'],
  'Kırklareli': ['Merkez', 'Babaeski', 'Demirköy', 'Kofçaz', 'Lüleburgaz', 'Pehlivanköy', 'Pınarhisar', 'Vize'],
  'Kırşehir': ['Merkez', 'Akçakent', 'Akpınar', 'Boztepe', 'Çiçekdağı', 'Kaman', 'Mucur'],
  'Kocaeli': ['İzmit', 'Gebze', 'Körfez', 'Darıca', 'Derince', 'Gölcük', 'Kartepe', 'Başiskele', 'Çayırova', 'Dilovası', 'Karamürsel', 'Kandıra'],
  'Konya': ['Selçuklu', 'Meram', 'Karatay', 'Akşehir', 'Ereğli', 'Seydişehir', 'Beyşehir', 'Ilgın', 'Cihanbeyli', 'Çumra', 'Kulu', 'Kadınhanı', 'Sarayönü', 'Altınekin', 'Ahırlı', 'Akören', 'Beysehir', 'Bozkır', 'Çeltik', 'Derbent', 'Derebucak', 'Doğanhisar', 'Emirgazi', 'Güneysınır', 'Halkapınar', 'Hadim', 'Hüyük', 'Karapınar', 'Taşkent', 'Tuzlukçu', 'Yalıhüyük', 'Yunak'],
  'Kütahya': ['Merkez', 'Altıntaş', 'Aslanapa', 'Çavdarhisar', 'Domaniç', 'Dumlupınar', 'Emet', 'Gediz', 'Hisarcık', 'Pazarlar', 'Şaphane', 'Simav', 'Tavşanlı'],
  'Malatya': ['Battalgazi', 'Yeşilyurt', 'Akçadağ', 'Arapgir', 'Arguvan', 'Darende', 'Doğanşehir', 'Doğanyol', 'Hekimhan', 'Kale', 'Kuluncak', 'Pütürge', 'Yazıhan'],
  'Manisa': ['Şehzadeler', 'Yunusemre', 'Akhisar', 'Turgutlu', 'Salihli', 'Soma', 'Alaşehir', 'Gördes', 'Kırkağaç', 'Saruhanlı', 'Ahmetli', 'Demirci', 'Gölmarmara', 'Kula', 'Köprübaşı', 'Selendi', 'Sarıgöl'],
  'Kahramanmaraş': ['Onikişubat', 'Dulkadiroğlu', 'Afşin', 'Andırın', 'Çağlayancerit', 'Ekinözü', 'Elbistan', 'Göksun', 'Nurhak', 'Pazarcık', 'Türkoğlu'],
  'Mardin': ['Artuklu', 'Kızıltepe', 'Midyat', 'Dargeçit', 'Derik', 'Mazıdağı', 'Nusaybin', 'Ömerli', 'Savur', 'Yeşilli'],
  'Muğla': ['Menteşe', 'Bodrum', 'Marmaris', 'Fethiye', 'Milas', 'Dalaman', 'Seydikemer', 'Datça', 'Köyceğiz', 'Kavaklıdere', 'Ortaca', 'Ula', 'Yatağan'],
  'Muş': ['Merkez', 'Bulanık', 'Hasköy', 'Korkut', 'Malazgirt', 'Varto'],
  'Nevşehir': ['Merkez', 'Acıgöl', 'Avanos', 'Derinkuyu', 'Gülşehir', 'Hacıbektaş', 'Kozaklı', 'Ürgüp'],
  'Niğde': ['Merkez', 'Altunhisar', 'Bor', 'Çamardı', 'Çiftlik', 'Ulukışla'],
  'Ordu': ['Altınordu', 'Ünye', 'Fatsa', 'Perşembe', 'Aybastı', 'Akkuş', 'Çamaş', 'Çatalpınar', 'Çaybaşı', 'Gölköy', 'Gülyalı', 'Gürgentepe', 'İkizce', 'Kabadüz', 'Kabataş', 'Korgan', 'Kumru', 'Mesudiye', 'Ulubey'],
  'Rize': ['Merkez', 'Ardeşen', 'Çamlıhemşin', 'Çayeli', 'Derepazarı', 'Fındıklı', 'Güneysu', 'Hemşin', 'İkizdere', 'İyidere', 'Kalkandere', 'Pazar'],
  'Sakarya': ['Adapazarı', 'Serdivan', 'Erenler', 'Arifiye', 'Akyazı', 'Hendek', 'Karasu', 'Kaynarca', 'Ferizli', 'Geyve', 'Söğütlü', 'Sapanca', 'Taraklı', 'Karapürçek', 'Kocaali', 'Pamukova'],
  'Samsun': ['İlkadım', 'Atakum', 'Canik', 'Bafra', 'Çarşamba', 'Terme', 'Vezirköprü', 'Havza', '19 Mayıs', 'Alaçam', 'Asarcık', 'Ayvacık', 'Kavak', 'Ladik', 'Salıpazarı', 'Tekkeköy', 'Yakakent'],
  'Siirt': ['Merkez', 'Baykan', 'Eruh', 'Kurtalan', 'Pervari', 'Şirvan', 'Tillo'],
  'Sinop': ['Merkez', 'Ayancık', 'Boyabat', 'Dikmen', 'Durağan', 'Erfelek', 'Gerze', 'Saraydüzü', 'Türkeli'],
  'Sivas': ['Merkez', 'Akıncılar', 'Altınyayla', 'Divriği', 'Doğanşar', 'Gemerek', 'Gölova', 'Gürün', 'Hafik', 'İmranlı', 'Kangal', 'Koyulhisar', 'Suşehri', 'Şarkışla', 'Ulaş', 'Yıldızeli', 'Zara'],
  'Tekirdağ': ['Süleymanpaşa', 'Çerkezköy', 'Çorlu', 'Ergene', 'Hayrabolu', 'Kapaklı', 'Malkara', 'Marmaraereğlisi', 'Muratlı', 'Saray', 'Şarköy'],
  'Tokat': ['Merkez', 'Almus', 'Artova', 'Başçiftlik', 'Erbaa', 'Niksar', 'Pazar', 'Reşadiye', 'Sulusaray', 'Turhal', 'Yeşilyurt', 'Zile'],
  'Trabzon': ['Ortahisar', 'Akçaabat', 'Araklı', 'Arsin', 'Beşikdüzü', 'Çarşıbaşı', 'Çaykara', 'Dernekpazarı', 'Düzköy', 'Hayrat', 'Köprübaşı', 'Maçka', 'Of', 'Şalpazarı', 'Sürmene', 'Tonya', 'Vakfıkebir', 'Yomra'],
  'Tunceli': ['Merkez', 'Çemişgezek', 'Hozat', 'Mazgirt', 'Nazımiye', 'Ovacık', 'Pertek', 'Pülümür'],
  'Şanlıurfa': ['Haliliye', 'Karaköprü', 'Eyyübiye', 'Siverek', 'Viranşehir', 'Akçakale', 'Birecik', 'Bozova', 'Ceylanpınar', 'Halfeti', 'Harran', 'Hilvan', 'Suruç'],
  'Uşak': ['Merkez', 'Banaz', 'Eşme', 'Karahallı', 'Sivaslı', 'Ulubey'],
  'Van': ['İpekyolu', 'Tuşba', 'Edremit', 'Başkale', 'Çaldıran', 'Çatak', 'Erciş', 'Gevaş', 'Gürpınar', 'Muradiye', 'Özalp', 'Saray', 'Bahçesaray'],
  'Yozgat': ['Merkez', 'Akdağmadeni', 'Aydıncık', 'Boğazlıyan', 'Çandır', 'Çayıralan', 'Çekerek', 'Kadışehri', 'Saraykent', 'Sarıkaya', 'Sorgun', 'Şefaatli', 'Yenifakılı', 'Yerköy'],
  'Zonguldak': ['Merkez', 'Alaplı', 'Çaycuma', 'Devrek', 'Ereğli', 'Gökçebey', 'Kilimli', 'Kozlu'],
  'Aksaray': ['Merkez', 'Ağaçören', 'Eskil', 'Gülağaç', 'Güzelyurt', 'Ortaköy', 'Sarıyahşi', 'Sultanhanı'],
  'Bayburt': ['Merkez', 'Aydıntepe', 'Demirözü'],
  'Karaman': ['Merkez', 'Ayrancı', 'Başyayla', 'Ermenek', 'Kazımkarabekir', 'Sarıveliler'],
  'Kırıkkale': ['Merkez', 'Bahşili', 'Balışeyh', 'Çelebi', 'Delice', 'Karakeçili', 'Keskin', 'Sulakyurt', 'Yahşihan'],
  'Batman': ['Merkez', 'Beşiri', 'Gercüş', 'Hasankeyf', 'Kozluk', 'Sason'],
  'Şırnak': ['Merkez', 'Beytüşşebap', 'Cizre', 'Güçlükonak', 'İdil', 'Silopi', 'Uludere'],
  'Bartın': ['Merkez', 'Amasra', 'Kurucaşile', 'Ulus'],
  'Ardahan': ['Merkez', 'Çıldır', 'Damal', 'Göle', 'Hanak', 'Posof'],
  'Iğdır': ['Merkez', 'Aralık', 'Karakoyunlu', 'Tuzluca'],
  'Yalova': ['Merkez', 'Altınova', 'Armutlu', 'Çınarcık', 'Çiftlikköy', 'Termal'],
  'Karabük': ['Merkez', 'Eflani', 'Eskipazar', 'Ovacık', 'Safranbolu', 'Yenice'],
  'Kilis': ['Merkez', 'Elbeyli', 'Musabeyli', 'Polateli'],
  'Osmaniye': ['Merkez', 'Bahçe', 'Düziçi', 'Hasanbeyli', 'Kadirli', 'Sumbas', 'Toprakkale'],
  'Düzce': ['Merkez', 'Akçakoca', 'Cumayeri', 'Çilimli', 'Gölyaka', 'Gümüşova', 'Kaynaşlı', 'Yığılca'],
};

export const TURKEY_CITIES = Object.keys(TURKEY_LOCATIONS).sort((a, b) => a.localeCompare(b, 'tr'));

export function getDistricts(city: string): string[] {
  return TURKEY_LOCATIONS[city] || [];
}
